import uns.ftn.siit.sbnz.proj.sbnz.model.Razvoj;
import uns.ftn.siit.sbnz.proj.sbnz.model.Zemljiste;
import uns.ftn.siit.sbnz.proj.sbnz.model.Usev;
import uns.ftn.siit.sbnz.proj.sbnz.model.UsevPodaci;
import uns.ftn.siit.sbnz.proj.sbnz.model.Konfiguracija;

import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.PodKategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.Povrsina;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaKlime;

import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipPovrsine;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.PodTipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipKlime;


global Razvoj razvoj;
dialect  "mvel"


declare Povrce
end

declare Voce
end


//PRAVILA NAGIBA

rule "nagib-normalno"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista <= 3 )
    then
        insert(new KategorijaNagiba(TipNagiba.RAVNO))
end

rule "nagib-konturno"
    when

        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 3 && $zemljiste.nagibZemljista <= 7 )
    then
        insert(new KategorijaNagiba(TipNagiba.KONTURNO))
end

rule "nagib-gusto-konturno"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 7 && $zemljiste.nagibZemljista <= 15 )
    then
        insert(new KategorijaNagiba(TipNagiba.GUSTO_KONTURNO))
end

rule "nagib-terasiranje"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 15 && $zemljiste.nagibZemljista <= 40 )
    then
        insert(new KategorijaNagiba(TipNagiba.TERASIRANJE))
end



//PRAVILA KLIME

rule "klima-hladna"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura<5)
    then
        insert(new KategorijaKlime(TipKlime.HLADNI))
end

rule "klima-umerena"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura>5 && $vreme.prosecnaGodisnjaTemperatura < 15)
    then
        insert(new KategorijaKlime(TipKlime.UMERENI))
end

rule "klima-zarka"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura > 15)
    then
        insert(new KategorijaKlime(TipKlime.ZARKI))
end



//PRAVILA POVRSINA
rule "provera-povrsine"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina == null)
    then
        $zemljiste.setPovrsina($zemljiste.getDuzina() * $zemljiste.getSirina());
        $konfig.setZemljiste($zemljiste);
        update($konfig);
end

rule "small"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina != null && $zemljiste.povrsina < 100)
    then
        insert(new Povrsina(TipPovrsine.SMALL))
end

rule "large"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina != null && $zemljiste.povrsina > 100)
    then
        insert(new Povrsina(TipPovrsine.LARGE))
end



// PRAVILA TIPOVA
rule "ratarski"
    when
        Povrsina(tipPovrsine == TipPovrsine.LARGE)
        KategorijaNagiba(tipNagiba ==TipNagiba.RAVNO || tipNagiba==TipNagiba.KONTURNO);
        KategorijaKlime(tipKlime == TipKlime.UMERENI||tipKlime == TipKlime.HLADNI)
    then
        insert(new KategorijaUseva(TipUseva.RATARSKI))
end

rule "vocni"
    when
        Povrsina(tipPovrsine == TipPovrsine.LARGE || tipPovrsine == TipPovrsine.SMALL)
        KategorijaNagiba(tipNagiba==TipNagiba.RAVNO || tipNagiba==TipNagiba.KONTURNO || tipNagiba==TipNagiba.GUSTO_KONTURNO || tipNagiba==TipNagiba.TERASIRANJE);
        KategorijaKlime(tipKlime == TipKlime.UMERENI || tipKlime == TipKlime.ZARKI )
    then
        insert(new KategorijaUseva(TipUseva.VOCNI))
end

rule "povrtarski"
    when
        Povrsina(tipPovrsine == TipPovrsine.LARGE || tipPovrsine == TipPovrsine.SMALL)
        KategorijaKlime(tipKlime == TipKlime.UMERENI || tipKlime == TipKlime.ZARKI || tipKlime == TipKlime.HLADNI)
    then
        insert(new KategorijaUseva(TipUseva.POVRTARSKI))
end



rule "specijalni"
    when
        Povrsina(tipPovrsine == TipPovrsine.LARGE || tipPovrsine == TipPovrsine.SMALL)
        KategorijaKlime(tipKlime == TipKlime.UMERENI || tipKlime == TipKlime.ZARKI || tipKlime == TipKlime.UMERENI)
    then
        insert(new KategorijaUseva(TipUseva.SPECIJALNI))
end

//PRETHODNI USEV


declare Prethodni
    usev: UsevPodaci
end

rule "prethodni-usev"
    when
        $konfig:Konfiguracija($pusevi: zemljiste.prethodniUsevi, zemljiste.prethodniUsevi.size() > 0);
        $usev: UsevPodaci() from $pusevi.get($pusevi.size()-1)
    then
        insert(new Prethodni($usev))
end


rule "luk-uslovi"
    when
        KategorijaUseva(tipUseva==TipUseva.POVRTARSKI)
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.phVrednost >= 6.0 && $zemljiste.phVrednost <= 7.5);
        Prethodni(usev.usev.podTipUseva == PodTipUseva.P_MAHUNARKE) or not Prethodni()
    then
        razvoj.getPonudaUseva().addUsev(new Usev("Beli luk", "Beli luk je vrsta luka bele boje izrazitog mirisa."));
        drools.getWorkingMemory().setGlobal("razvoj", razvoj);
end
