package sbnz.integracija

import uns.ftn.siit.sbnz.proj.sbnz.model.Razvoj;
import uns.ftn.siit.sbnz.proj.sbnz.model.Zemljiste;
import uns.ftn.siit.sbnz.proj.sbnz.model.Usev;
import uns.ftn.siit.sbnz.proj.sbnz.model.UsevPodaci;
import uns.ftn.siit.sbnz.proj.sbnz.model.PonudaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.Konfiguracija;

import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.PodKategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.Povrsina;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaKlime;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaKiselosti;

import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipPovrsine;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.PodTipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipKlime;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipKiselosti

dialect  "mvel"

declare Prethodni
    usev: UsevPodaci
end

rule "prethodni-usev"
    when
        $konfig:Konfiguracija($pusevi: zemljiste.prethodniUsevi, zemljiste.prethodniUsevi.size() > 0)
        $usev: UsevPodaci() from $pusevi.get($pusevi.size()-1)
   then
        Prethodni prethodni = new Prethodni();
        prethodni.setUsev($usev);
        insert(prethodni);
end

rule "luk-uslovi"
    when
        KategorijaUseva(tipUseva==TipUseva.POVRTARSKI);
        $r : Razvoj( $usevi : ponudaUseva);
        not Usev(naziv=="Beli luk") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Alkalno);
        Prethodni(usev.usev.podTipUseva == PodTipUseva.P_MAHUNARKE) or not Prethodni()
    then
    	$usevi.addUsev(new Usev("Beli luk", "Beli luk je vrsta luka bele boje izrazitog mirisa."));
        update($r);
end


rule "zelena-salata-uslovi"
    no-loop
    when
        KategorijaUseva(tipUseva==TipUseva.POVRTARSKI)
        $r: Razvoj( $usevi : ponudaUseva)
        not Usev(naziv=="Zelena salata") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Bazno);
        Prethodni(usev.usev.podTipUseva == PodTipUseva.P_MAHUNARKE) or not Prethodni()
        
    then
    	$usevi.addUsev(new Usev("Zelena salata", "Salata je vrsta zelenog povrca."));
        update($r);
end


rule "breskva-uslovi"
	no-loop
	when
        KategorijaUseva(tipUseva==TipUseva.VOCNI)
        $r : Razvoj( $usevi : ponudaUseva)
        not Usev(naziv=="Breskva") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Bazno);
    then
    	$usevi.addUsev(new Usev("Breskva", "Breksva spada u slatko voce poreklom iz Kine"));
    	update($r);
end




rule "malina-uslovi"
	no-loop
	when
        KategorijaUseva(tipUseva==TipUseva.VOCNI)
        $r : Razvoj( $usevi : ponudaUseva)
        not Usev(naziv=="Malina") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Kiselo);
        not Prethodni(usev.usev.podTipUseva == PodTipUseva.V_KOSTUNICAVI)
    then
    	$usevi.addUsev(new Usev("Malina", "Malina spada u slatko voce poreklom iz Spanije"));
    	update($r);
end


rule "borovnica-uslovi"
	no-loop
	when
        KategorijaUseva(tipUseva==TipUseva.VOCNI)
        $r : Razvoj( $usevi : ponudaUseva)
        not Usev(naziv=="Borovnica") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Kiselo);
    then
    	$usevi.addUsev(new Usev("Borovnica", "Borovnica spada u bobicasto voce"));
    	update($r);
end


rule "psenica-uslovi"
	no-loop
	when
        KategorijaUseva(tipUseva==TipUseva.RATARSKI)
        $r : Razvoj( $usevi : ponudaUseva)
        not Usev(naziv=="Psenica") from $usevi.ponude
        KategorijaKiselosti(tipKiselosti==TipKiselosti.Bazno);
    then
    	$usevi.addUsev(new Usev("Psenica", "Psenica predstavlja jednostavno ratarsku kulturu"));
    	update($r);
end

