import uns.ftn.siit.sbnz.proj.sbnz.model.Razvoj;
import uns.ftn.siit.sbnz.proj.sbnz.model.Zemljiste;
import uns.ftn.siit.sbnz.proj.sbnz.model.Usev;
import uns.ftn.siit.sbnz.proj.sbnz.model.Konfiguracija;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.PodKategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.Povrsina;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.Povrsina.TipPovrsine;

import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.PodTipUseva;


global Razvoj razvoj;
dialect  "mvel"


declare Povrce
end

declare Voce
end


declare Normalno
end
declare Konturno
end
declare GustoKonturno
end
declare Terasiranje
end

//PRAVILA NAGIBA

rule "nagib-normalno"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista <= 3 )
    then
        insert(new Normalno())
end

rule "nagib-konturno"
    when

        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 3 && $zemljiste.nagibZemljista <= 7 )
    then
        insert(new Konturno())
end

rule "nagib-gusto-konturno"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 7 && $zemljiste.nagibZemljista <= 15 )
    then
        insert(new GustoKonturno())
end

rule "nagib-terasiranje"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.nagibZemljista > 15 && $zemljiste.nagibZemljista <= 40 )
    then
        insert(new Terasiranje())
end



declare Hladna
end
declare Umerena
end
declare Zarka
end

//PRAVILA KLIME

rule "klima-hladna"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura<5)
    then
        insert(new Hladna())
end

rule "klima-umerena"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura>5 && $vreme.prosecnaGodisnjaTemperatura < 15)
    then
        insert(new Umerena())
end

rule "klima-zarka"
    when
        $konfig:Konfiguracija($vreme: vremenskiPodaci, $vreme.prosecnaGodisnjaTemperatura > 15)
    then
        insert(new Zarka())
end

//PRAVILA POVRSINA
rule "provera-povrsine"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina == null)
    then
        $zemljiste.setPovrsina($zemljiste.getDuzina() * $zemljiste.getSirina());
        $konfig.setZemljiste($zemljiste);
        update($konfig);
end



rule "small"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina != null && $zemljiste.povrsina < 100)
    then
        insert(new Povrsina(TipPovrsine.SMALL))
end

rule "large"
    when
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.povrsina != null && $zemljiste.povrsina > 100)
    then
        insert(new Povrsina(TipPovrsine.LARGE))
end



// PRAVILA TIPOVA

rule "zarka-normalanTeren"
    when
        Umerena();
        Terasiranje();
    then
        insert(new KategorijaUseva(TipUseva.VOCNI))
        insert(new KategorijaUseva(TipUseva.POVRTARSKI))
end

rule "zarka-normalanTeren"
    when
        Normalno();
        Umerena();
    then
        insert(new KategorijaUseva(TipUseva.VOCNI))
        insert(new KategorijaUseva(TipUseva.POVRTARSKI))
        insert(new KategorijaUseva(TipUseva.RATARSKI))
end









rule "luk-uslovi"
    when
        KategorijaUseva(tipUseva==TipUseva.POVRTARSKI)
        $konfig:Konfiguracija($zemljiste: zemljiste, $zemljiste.phVrednost >= 6.0 && $zemljiste.phVrednost <= 7.5)
    then
        razvoj.getPonudaUseva().addUsev(new Usev("Beli luk", "Beli luk je vrsta luka bele boje izrazitog mirisa."));
        drools.getWorkingMemory().setGlobal("razvoj", razvoj);
end
