import uns.ftn.siit.sbnz.proj.sbnz.model.Razvoj;
import uns.ftn.siit.sbnz.proj.sbnz.model.Zemljiste;
import uns.ftn.siit.sbnz.proj.sbnz.model.Usev;
import uns.ftn.siit.sbnz.proj.sbnz.model.Konfiguracija;

global Razvoj razvoj;
dialect  "mvel"

rule "odabir-useva"
    when
        $konfig:Konfiguracija(zemljiste.povrsina > 100)
    then
        razvoj.setOdabraniUsev(new Usev("Patlidzan"));
        drools.getWorkingMemory().setGlobal("razvoj", razvoj);
end

rule "odabir-useva-1"
    when
        $zemljiste:Zemljiste(povrsina <= 100)
    then
        System.out.println("SARGAREPA");
        razvoj.setOdabraniUsev(new Usev("Sargarepa"));
        drools.getWorkingMemory().setGlobal("razvoj", razvoj);
end