package sbnz.integracija

import uns.ftn.siit.sbnz.proj.sbnz.model.Razvoj;
import uns.ftn.siit.sbnz.proj.sbnz.model.Zemljiste;
import uns.ftn.siit.sbnz.proj.sbnz.model.Usev;
import uns.ftn.siit.sbnz.proj.sbnz.model.UsevPodaci;
import uns.ftn.siit.sbnz.proj.sbnz.model.Konfiguracija;
import uns.ftn.siit.sbnz.proj.sbnz.model.StanjeUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.VremenskaPrognoza;
import uns.ftn.siit.sbnz.proj.sbnz.model.Akcija;


import uns.ftn.siit.sbnz.proj.sbnz.model.Uslov;
import uns.ftn.siit.sbnz.proj.sbnz.model.UsloviAkcija;


import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.PodKategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.Povrsina;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaUseva;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.medjuklase.KategorijaKlime;

import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipPovrsine;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.PodTipUseva;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipNagiba;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipKlime;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipPadavine;
import uns.ftn.siit.sbnz.proj.sbnz.model.enums.TipStanjaZemljista;

import uns.ftn.siit.sbnz.proj.sbnz.service.RazvojService;
import uns.ftn.siit.sbnz.proj.sbnz.service.AlertService;


import java.util.Date;

import function com.sample.Utility.help;


dialect  "mvel";


declare TrenutnoVreme
	trenutnoVreme:Date

end

global RazvojService razvojService;
global AlertService alertService;


function void saveRazvoj(RazvojService razvojService, Razvoj r) {
    razvojService.saveRazvoj(r);
}


//rule "trenutno-vreme-exists"
//    when
//        Razvoj(odabraniUsev.naziv=="Beli luk")
//        not TrenutnoVreme()
//    then
//        TrenutnoVreme trenutnoVreme = new TrenutnoVreme();
//        trenutnoVreme.setTrenutnoVreme(new java.util.Date(
//                drools
//                    .getWorkingMemory()
//                    .getSessionClock()
//                    .getCurrentTime()
//            )
//
//        );
//		insert(trenutnoVreme)
//        help(drools, trenutnoVreme.getTrenutnoVreme().toString())
//end
//
//rule "trenutno-vreme"
//    timer(int: 0s 1d)
//    when
//        $razvoj:Razvoj($akcije: trenutnaAkcija, odabraniUsev.naziv=="Beli luk")
//        $vreme : TrenutnoVreme()
//    then
//        $vreme.setTrenutnoVreme(
//            new java.util.Date(
//                 drools
//                     .getWorkingMemory()
//                     .getSessionClock()
//                     .getCurrentTime()
//             )
//        );
//        help(drools, $vreme.getTrenutnoVreme().toString());
//		update($vreme);
//end

rule "zemljiste-info"
    when
        $razvoj:Razvoj($akcije: trenutnaAkcija, $o: odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Unos informacija o zemljistu") from $akcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista==null)
    then
        Akcija a = new Akcija("Unos informacija o zemljistu", "Potrebno je uneti informacije o zemljistu(vlaznost, stanje...)");
        $akcije.add(a);
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-bacanje-8-16-24"
    timer(cron: 0 6 * 9 *)
    when
        $razvoj:Razvoj($akcije: trenutnaAkcija, $iakcije: istorijaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Djubrenje pred oranje") from $akcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista!=null, trenutnoStanjeZemljista.stanje==TipStanjaZemljista.TVRDO)
    then
        alertService.dodajAlert($razvoj,  new Akcija("Djubrenje pred oranje", "Potrebno je baciti vestacko djubrivo odnosa 8-16-24 NPK pred oranje."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-oranje"
    timer(cron: 0 6 * 9 *)
    when
        $razvoj:Razvoj($akcije: trenutnaAkcija, $iakcije: istorijaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Sadjenje belog luka") from $akcije
        Akcija(naziv=="Djubrenje pred oranje") from $akcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista!=null, trenutnoStanjeZemljista.stanje==TipStanjaZemljista.TVRDO)
    then
        alertService.dodajAlert($razvoj,  new Akcija("Duboko oranje zemljista", "Potrebno je odraditi duboko oranje."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-kultivisanje"
    timer(cron: 0 6 * 9 *)
    when
        $razvoj:Razvoj($akcije: trenutnaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Sadjenje belog luka") from $akcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista!=null, trenutnoStanjeZemljista.stanje==TipStanjaZemljista.IZORANO || trenutnoStanjeZemljista.stanje==TipStanjaZemljista.MEKO)
    then
        alertService.dodajAlert($razvoj,  new Akcija("Kultivisanje zemljista", "Potrebno je odraditi kultivisanje zemljista dok zemljiste ne postane fino ili sitno i spremno za sadnju."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-sadjenje"
    timer(cron: 0 6 0-15 10 *)
    when
        VremenskaPrognoza(tipPadavine == TipPadavine.KISA) over window:length(3)
        $razvoj:Razvoj($akcije: trenutnaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Sadjenje belog luka") from $akcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista!=null,trenutnoStanjeZemljista.procenatVlage<12, trenutnoStanjeZemljista.stanje==TipStanjaZemljista.FINO)
    then
        alertService.dodajAlert($razvoj,  new Akcija("Sadjenje belog luka", "Potrebno posaditi beli luk"));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-zalivanje-posle-sadjenja"
    timer(cron: 0 6 0/10 10-11 *)
    when
        not VremenskaPrognoza(tipPadavine == TipPadavine.KISA) over window:length(10)
        $razvoj:Razvoj($akcije: trenutnaAkcija, $iakcije: istorijaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Zalivanje posle sadjenja") from $akcije
        Akcija(naziv=="Sadjenje belog luka") from $iakcije
        $zemljiste:Zemljiste(trenutnoStanjeZemljista!=null,trenutnoStanjeZemljista.procenatVlage<12)
    then
        alertService.dodajAlert($razvoj,  new Akcija("Zalivanje posle sadjenja", "Potrebno je zaliti luk nakon sadnje zbog male vlage u zemljistu."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end

rule "luk-herbicid-posle-sadjenja"
    when
        not VremenskaPrognoza(tipPadavine == TipPadavine.KISA) over window:length(1)
        $razvoj:Razvoj($akcije: trenutnaAkcija, $iakcije: istorijaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Herbicid nakon sadjenja") from $akcije
        not Akcija(naziv=="Herbicid nakon sadjenja") from $iakcije
        Akcija(naziv=="Sadjenje belog luka") from $iakcije
    then
        alertService.dodajAlert($razvoj,  new Akcija("Herbicid nakon sadjenja", "Potrebno je isprskati luk herbicidom nakon sadnje radi zastite od korova."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end



rule "luk-fungicid"
    timer(cron: 0 6 0/10 3 *)
    when
        not VremenskaPrognoza(tipPadavine == TipPadavine.KISA) over window:length(1)
        $razvoj:Razvoj($akcije: trenutnaAkcija, $iakcije: istorijaAkcija, odabraniUsev.naziv=="Beli luk")
        not Akcija(naziv=="Prskanje fungicidom") from $akcije
    then
        alertService.dodajAlert($razvoj,  new Akcija("Prskanje fungicidom", "Potrebno je isprskati luk fungicidom nakon sadnje radi zastite od plamenjace."));
        update($razvoj)
        saveRazvoj(razvojService, $razvoj);
        help(drools, "----------------------------> Uspeh");
end
//
//rule "zemljiste-info"
//    lock-on-active
//    when
//        $razvoj:Razvoj($akcije: trenutnaAkcija)
//        $zemljiste:Zemljiste(trenutnoStanjeZemljista==null)
//    then
//        Akcija a = new Akcija("Unos informacija o zemljistu", "Potrebno je uneti informacije o zemljistu(vlaznost, stanje...)", $razvoj);
//        $akcije.add(a);
//        update($razvoj)
//        saveRazvoj(razvojService, $razvoj);
//        help(drools, "----------------------------> Uspeh");
//end


